version: '3'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: maria
      POSTGRES_PASSWORD: Postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-networks


  app:
    build: .
    command: python app.py
    volumes:
      - .:/app    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://maria:Postgres@db:5432/madatabase
    depends_on:
      - db
    networks:
      - app-networks

networks:
  app-networks:
    # driver: bridge

volumes:
  postgres_data:
