apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-name

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: init-db-check
        image: busybox
        command: ['sh', '-c', 'until nslookup postgre-service; do echo waiting for db; sleep 2; done']

      containers:
      - name: app
        image: mariambodji/app:latest
        ports:
        - containerPort: 5000
        env:
            - name: DATABASE_HOST
              value: "app-service"
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: database_name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: database_password
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        